name: odpic-raw
version: 0.4.1
synopsis: Oracle Database Bindings
description: A low-level client library for the Oracle database, implemented as bindings to the C ODPI API.
maintainer: Daniel YU <leptonyu@gmail.com>
license: MIT
github: leptonyu/odpic-raw
category: Database, Oracle, ODPI-C, FFI, Raw
extra-source-files: 
- README.md
- include/LICENSE
- include/*.h
- include/*.c

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - resourcet
  - conduit
  - time
  - scientific
  - binary

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - Database.Dpi
    - Database.Dpi.Field
    - Database.Dpi.Sql
  other-modules:
    - Database.Dpi.Internal
    - Database.Dpi.Prelude
    - Database.Dpi.Util
  include-dirs: 
  - include
  c-sources:
  - include/*.c
  build-tools: c2hs

tests:
  odpic-raw-test:
    source-dirs: test
    main: Spec.hs
    build-tools: c2hs
    dependencies:
      - odpic-raw
      - resourcet
      - conduit
      - bytestring
      - hspec
